<form name="personalInfoForm" class="formGrid" >
    <?php foreach ($this->fields as $field): ?>
        <?php echo $field ?>
    <?php endforeach ?><br />
    <input type="button" id="save" value="<?php echo $this->translate('Save') ?>" onclick="COMMID.editPersonalInfo.save()" />
    <input type="button" id="cancel" value="<?php echo $this->translate('Cancel') ?>" onclick="COMMID.editPersonalInfo.cancel()" />
    <script type="text/javascript">
        YAHOO.util.Event.onDOMReady(function () {
            COMMID.loader.insert(
                ["connection"],
                null
            );
        });

        var oButton = new YAHOO.widget.Button(
            "save",
            {
                type    : "push",
                onclick : {fn: COMMID.personalInfo.save}
            }
        );
        var oButton = new YAHOO.widget.Button(
            "cancel",
            {
                type    : "push",
                onclick : {fn: COMMID.personalInfo.cancel}
            }
        );
    </script> 
</form>
