<div class="formGrid">
    <?php foreach ($this->fields as $field): ?>
        <div class="yui-gf">
            <div class="yui-u first">
                <?php echo $this->translate($field->name) ?>:
            </div>
            <div class="yui-u">
                <?php echo is_null($field->value)? $this->translate('Not Entered') : $field->value  ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
