<h3><?= $this->translate('In order to serve you better, we have provided the form below for your questions and comments') ?></h3>
<form id="feedbackForm" method="post" action="<?= $this->base ?>/feedback/send" class="formGrid">
    <?= $this->form->name ?>
    <?= $this->form->email ?>
    <?= $this->form->feedback ?>
    <?= $this->form->captcha ?>
    <input type="submit" id="send" value="<?= $this->translate('Send') ?>" />
    <script type="text/javascript">
        var oButton = new YAHOO.widget.Button("send");
    </script> 
</form>
