<h3>
    <?= $this->translate('Database and E-mail information') ?>
</h3>
<form name="installform" method="post" action="<?= $this->base ?>/install/credentials/save" class="longLabelsForm">
    <dl>
        <?= $this->form->hostname ?>
        <?= $this->form->dbname ?>
        <?= $this->form->dbusername ?>
        <?= $this->form->dbpassword ?>
        <?= $this->form->supportemail ?>
    </dl>
    <input type="submit" id="send" value="<?= $this->translate('Send') ?>" />
    <script type="text/javascript">
        var oButton = new YAHOO.widget.Button("send");
    </script> 
</form>
