<h3><?php echo $this->translate('Authorizations per day') ?></h3>
<div>
    <?php echo $this->translate('Select view') ?>:
    <select name="view" onchange="COMMID.stats.loadReport('authorizations', 'statsAuths', 'type=' + this.value)">
        <option value="week" <?php echo $this->weekSelected ?>><?php echo $this->translate('Last Week') ?></option>
        <option value="year" <?php echo $this->yearSelected ?>><?php echo $this->translate('Last Year') ?></option>
    </select>
</div>
<img src="<?php echo $this->base ?>/stats/authorizations/graph?rand=<?php echo $this->rand ?>&type=<?php echo $this->type ?>" />

