<h3><?= $this->translate('Trusted Sites') ?></h3>
<div>
    <?= $this->translate('Select view') ?>:
    <select name="view" onchange="COMMID.stats.loadReport('sites', 'statsNumTrustedSites', 'type=' + this.value)">
        <option value="week" <?= $this->weekSelected ?>><?= $this->translate('Last Week') ?></option>
        <option value="year" <?= $this->yearSelected ?>><?= $this->translate('Last Year') ?></option>
    </select>
</div>
<img src="<?= $this->base ?>/stats/sites/graph?rand=<?= $this->rand ?>&type=<?= $this->type ?>" />
