<h3><?php echo $this->translate('Registrations per day') ?></h3>
<div>
    <?php echo $this->translate('Select view') ?>:
    <select name="view" onchange="COMMID.stats.loadReport('registrations', 'statsRegs', 'type=' + this.value)">
        <option value="week" <?php echo $this->weekSelected ?>><?= $this->translate('Last Week') ?></option>
        <option value="month" <?php echo $this->monthSelected ?>><?= $this->translate('Last Month') ?></option>
        <option value="year" <?php echo $this->yearSelected ?>><?= $this->translate('Last Year') ?></option>
    </select>
</div>
<img src="<?php echo $this->base ?>/stats/registrations/graph?rand=<?= $this->rand ?>&type=<?= $this->type ?>" />
